# Meta Data for SEO

## Homepage
title = "Nebula"
titleSeparator = "-"
titleAddition = "Promega Design System"
description = "Nebula is Promega's digital design system."

## Open Graph + Twitter Cards
# images = ["doks.png"]
# twitterSite = "henkverlinde"
# twitterCreator = "henkverlinde"
# facebookAuthor = "verlinde.henk"
# facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
# schemaType = "Organization"
# schemaLogo = "logo-doks.png"
# schemaTwitter = "https://twitter.com/henkverlinde"
# schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
# schemaGitHub = "https://github.com/h-enk"
# schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a> & <a href=\"https://getdoks.org/\">Doks</a>"

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
